export const d = {
	customer: {
		name: "Michal Gerhát",
	},
	supplyer: {
		company_name: "STAV-IL s.r.o.",
		ico: "56 945 124",
		dic: "5487961254",
		phone: "0945687214",
		email: "stavil@gmail.com",
		web: "www.stavil.sk",
	},
	headers: [
		"service_type",
		"item_id",
		"title",
		"unit",
		"quantity",
		"unit_delivery_price",
		"unit_construction_price",
		"total_delivery_price",
		"total_construction_price",
		"total",
	],
	blocks: [
		{
			info: {
				title: "Zemné práce",
				total_delivery_price: 0,
				total_construction_price: 1909.4288000000001,
				total: 0,
			},
			items: [
				{
					service_type: 0,
					item_id: "000300016.S",
					title:
						"Geodetické práce - vykonávané pred výstavbou určenie vytyčovacej siete, vytýčenie staveniska, staveb. objektu",
					unit: "diel",
					quantity: 1,
					unit_delivery_price: 0,
					unit_construction_price: 150,
					total_delivery_price: 0,
					total_construction_price: 150,
				},
				{
					service_type: "R",
					item_id: 121101111,
					title:
						"Odstránenie ornice s vodor. premiestn. na hromady, so zložením na vzdialenosť do 100 m a nad 100m3",
					unit: "m3",
					quantity: 37.2,
					unit_delivery_price: 0,
					unit_construction_price: 2.12,
					total_delivery_price: 0,
					total_construction_price: 78.864,
				},
				{
					service_type: "R",
					item_id: 132201101,
					title: "Výkop ryhy do šírky 600 mm v horn.3 do 100 m3",
					unit: "m3",
					quantity: 60,
					unit_delivery_price: 0,
					unit_construction_price: 12.51,
					total_delivery_price: 0,
					total_construction_price: 750.6,
				},
				{
					service_type: "R",
					item_id: 122201102,
					title: "Odkopávka nezapažená v hornine3., nad 100 do 1000 m3",
					unit: "m3",
					quantity: 6.74,
					unit_delivery_price: 0,
					unit_construction_price: 3.78,
					total_delivery_price: 0,
					total_construction_price: 25.4772,
				},
				{
					service_type: "R",
					item_id: 162201101,
					title: "Vodorovné premiestnenie výkopku z horniny 1-4 do 20m",
					unit: "m3",
					quantity: 60,
					unit_delivery_price: 0,
					unit_construction_price: 7.21,
					total_delivery_price: 0,
					total_construction_price: 432.6,
				},
				{
					service_type: "R",
					item_id: 167101102,
					title:
						"Nakladanie neuľahnutého výkopku z hornín tr.1-4 nad 100 do 1000 m3",
					unit: "m3",
					quantity: 103.94,
					unit_delivery_price: 0,
					unit_construction_price: 2.91,
					total_delivery_price: 0,
					total_construction_price: 302.4654,
				},
				{
					service_type: "R",
					item_id: 171201202,
					title: "Uloženie sypaniny na skládky nad 100 do 1000 m3",
					unit: "m3",
					quantity: 103.94,
					unit_delivery_price: 0,
					unit_construction_price: 1.63,
					total_delivery_price: 0,
					total_construction_price: 169.42219999999998,
				},
			],
		},
		{
			info: {
				title: "Zakladanie",
				total_delivery_price: 10353.896949999998,
				total_construction_price: 1930.7211249999998,
				total: 0,
			},
			items: [
				{
					service_type: "R",
					item_id: 271573001,
					title:
						"Násyp pod základové konštrukcie so zhutnením zo štrkopiesku fr.32-63 mm",
					unit: "m3",
					quantity: 66.25,
					unit_delivery_price: 14.78,
					unit_construction_price: 3.47,
					total_delivery_price: 979.175,
					total_construction_price: 229.88750000000002,
				},
				{
					service_type: "R",
					item_id: 27332131,
					title:
						"Betón základových dosiek, železový (bez výstuže), tr. C 20/25",
					unit: "m3",
					quantity: 23.25,
					unit_delivery_price: 85.36,
					unit_construction_price: 22.12,
					total_delivery_price: 1984.62,
					total_construction_price: 514.2900000000001,
				},
				{
					service_type: "R",
					item_id: 273362422,
					title:
						"Výstuž základových dosiek zo zvár. sietí KARI, priemer drôtu 8 mm, veľkosť oka 150x150 mm",
					unit: "m2",
					quantity: 193.75,
					unit_delivery_price: 9.7,
					unit_construction_price: 0.78,
					total_delivery_price: 1879.3749999999998,
					total_construction_price: 151.125,
				},
				{
					service_type: "R",
					item_id: 274271300,
					title:
						"Murivo základových pásov (m3) PREMAC 50x40x25 s betónovou výplňou                    C 20/25 hr. 400 mm",
					unit: "m3",
					quantity: 1,
					unit_delivery_price: 136.24,
					unit_construction_price: 44.87,
					total_delivery_price: 136.24,
					total_construction_price: 44.87,
				},
				{
					service_type: "R",
					item_id: 274271303,
					title:
						"Murivo základových pásov (m3) PREMAC 50x30x25 s betónovou výplňou                    C 20/25 hr. 300 mm",
					unit: "m3",
					quantity: 15,
					unit_delivery_price: 134.88,
					unit_construction_price: 42.73,
					total_delivery_price: 2023.1999999999998,
					total_construction_price: 640.9499999999999,
				},
				{
					service_type: "R",
					item_id: 274271312,
					title:
						"Murivo základových pásov (m3) PREMAC 50x25x25 s betónovou výplňou                C 20/25 hr. 250 mm",
					unit: "m3",
					quantity: 0,
					unit_delivery_price: 132.72,
					unit_construction_price: 40.56,
					total_delivery_price: 0,
					total_construction_price: 0,
				},
				{
					service_type: "R",
					item_id: 274271311,
					title:
						"Murivo základových pásov (m3) PREMAC 50x20x25 s betónovou výplňou                 C 20/25 hr. 200 mm",
					unit: "m3",
					quantity: 0,
					unit_delivery_price: 131.59,
					unit_construction_price: 39.36,
					total_delivery_price: 0,
					total_construction_price: 0,
				},
				{
					service_type: "R",
					item_id: 274321312,
					title: "Betón základových pásov, železový (bez výstuže), tr. C 16/20",
					unit: "m3",
					quantity: 36,
					unit_delivery_price: 82.91,
					unit_construction_price: 8.37,
					total_delivery_price: 2984.7599999999998,
					total_construction_price: 301.32,
				},
				{
					service_type: "R",
					item_id: 274361825,
					title:
						"Výstuž pre murivo základových pásov PREMAC s betónovou výplňou z ocele 10505",
					unit: "t",
					quantity: 0.3875,
					unit_delivery_price: 945.876,
					unit_construction_price: 124.59,
					total_delivery_price: 366.52695,
					total_construction_price: 48.278625000000005,
				},
			],
		},
		{
			info: {
				title: "Zvislé konštrukcie",
				total_delivery_price: 703.075,
				total_construction_price: 204.36499999999998,
				total: 0,
			},
			items: [
				{
					service_type: "R",
					item_id: 451572111,
					title:
						"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z kameniva drobného ťaženého 0-4 mm",
					unit: "m3",
					quantity: 4,
					unit_delivery_price: 24,
					unit_construction_price: 17.97,
					total_delivery_price: 96,
					total_construction_price: 71.88,
				},
				{
					service_type: "R",
					item_id: 451573111,
					title:
						"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z piesku a štrkopiesku do 63 mm",
					unit: "m3",
					quantity: 2.5,
					unit_delivery_price: 21.07,
					unit_construction_price: 13.97,
					total_delivery_price: 52.675,
					total_construction_price: 34.925000000000004,
				},
				{
					service_type: "R",
					item_id: 2837650030,
					title:
						"Doska XPS STYRODUR 2800 C hr. 100 mm, zateplenie soklov, suterénov, podláh, ISOVER",
					unit: "m2",
					quantity: 36,
					unit_delivery_price: 13.89,
					unit_construction_price: 2.15,
					total_delivery_price: 500.04,
					total_construction_price: 77.39999999999999,
				},
				{
					"Č.": 20,
					service_type: "R",
					item_id: 283230000800,
					title:
						"Profilovaná fólia z PE DELTA-NB, rozmer 20x0,5m, pevnosť v tlaku 200 kN/m2, pre spodnú stavbu, DORKEN",
					unit: "m2",
					quantity: 36,
					unit_delivery_price: 1.51,
					unit_construction_price: 0.56,
					total_delivery_price: 54.36,
					total_construction_price: 20.160000000000004,
				},
			],
		},
		{
			info: {
				title: "Presun hmôt HSV",
				total_delivery_price: 0,
				total_construction_price: 321.99700000000007,
				total: 0,
			},
			items: [
				{
					service_type: "R",
					item_id: 998011001,
					title:
						"Presun hmôt pre budovy (801, 803, 812), zvislá konštr. z tehál, tvárnic, z kovu výšky do 6 m",
					unit: "t",
					quantity: 20.150000000000002,
					unit_delivery_price: 0,
					unit_construction_price: 15.98,
					total_delivery_price: 0,
					total_construction_price: 321.99700000000007,
				},
			],
		},
		{
			info: {
				title: "Práce a dodávky PSV",
				total_delivery_price: 1033.11,
				total_construction_price: 312.4,
				total: 0,
			},
			items: [],
		},
		{
			info: {
				title: "Zdravotechnika - vnútorná kanalizácia",
				total_delivery_price: 643.41,
				total_construction_price: 211.74,
				total: 0,
			},
			items: [
				{
					service_type: "R",
					item_id: 721171309,
					title: "Potrubie z rúr PE GEBERIT 125/4, 9 odpadné v zemi",
					unit: "m",
					quantity: 31,
					unit_delivery_price: 13.49,
					unit_construction_price: 5.07,
					total_delivery_price: 418.19,
					total_construction_price: 157.17000000000002,
				},
				{
					service_type: 286,
					item_id: "286510003800.S",
					title:
						"Koleno PVC-U, DN 125x15°, 30°, 45° pre pre hladký, kanalizačný, gravitačný systém",
					unit: "ks",
					quantity: 39,
					unit_delivery_price: 3.22,
					unit_construction_price: 0.64,
					total_delivery_price: 125.58000000000001,
					total_construction_price: 24.96,
				},
				{
					service_type: 286,
					item_id: 286130048900,
					title:
						"Rúra HDPE PE100 D 32x2,9 mm, dĺ. 100 m PN 16 (SDR11) pre tlakový rozvod pitnej vody, PIPELIFE",
					unit: "m",
					quantity: 47,
					unit_delivery_price: 2.12,
					unit_construction_price: 0.63,
					total_delivery_price: 99.64,
					total_construction_price: 29.61,
				},
			],
		},
		{
			info: {
				title: "Elektromontáže",
				total_delivery_price: 389.7,
				total_construction_price: 100.66,
				total: 0,
			},
			items: [
				{
					service_type: 345,
					item_id: 345710009300,
					title: "Rúrka ohybná vlnitá pancierová PVC-U, FXP DN 63",
					unit: "m",
					quantity: 40,
					unit_delivery_price: 1.05,
					unit_construction_price: 0.25,
					total_delivery_price: 42,
					total_construction_price: 10,
				},
				{
					service_type: "R",
					item_id: 210220020,
					title: "Uzemňovacie vedenie v zemi FeZn vrátane izolácie spojov",
					unit: "bm",
					quantity: 66,
					unit_delivery_price: 1.05,
					unit_construction_price: 0.51,
					total_delivery_price: 69.3,
					total_construction_price: 33.660000000000004,
				},
				{
					service_type: "R",
					item_id: 354410058800,
					title: "Pásovina uzemňovacia FeZn 30 x 4 mm",
					unit: "bm",
					quantity: 66,
					unit_delivery_price: 3.2,
					unit_construction_price: 0.5,
					total_delivery_price: 211.20000000000002,
					total_construction_price: 33,
				},
				{
					service_type: "R",
					item_id: 354410054800,
					title: "Drôt bleskozvodový FeZn, d 10mm",
					unit: "bm",
					quantity: 48,
					unit_delivery_price: 1.4,
					unit_construction_price: 0.5,
					total_delivery_price: 67.19999999999999,
					total_construction_price: 24,
				},
			],
		},
	],
};

export const newd = {
	customer: {
		name: "Michal Gerhát",
	},
	supplyer: {
		company_name: "STAV-IL s.r.o.",
		ico: "56 945 124",
		dic: "5487961254",
		phone: "0945687214",
		email: "stavil@gmail.com",
		web: "www.stavil.sk",
	},
	headers: [
		"service_type",
		"item_id",
		"title",
		"unit",
		"quantity",
		"unit_delivery_price",
		"unit_construction_price",
		"total_delivery_price",
		"total_construction_price",
		"total",
	],
	sections: [
		{
			info: {
				title: "Základová doska",
				total_delivery_price: 0,
				total_construction_price: 1909.4288000000001,
				total: 0,
			},
			blocks: [
				{
					info: {
						title: "Zemné práce",
						total_delivery_price: 0,
						total_construction_price: 1909.4288000000001,
						total: 0,
					},
					items: [
						{
							service_type: 0,
							item_id: "000300016.S",
							title:
								"Geodetické práce - vykonávané pred výstavbou určenie vytyčovacej siete, vytýčenie staveniska, staveb. objektu",
							unit: "diel",
							quantity: 1,
							unit_delivery_price: 0,
							unit_construction_price: 150,
							total_delivery_price: 0,
							total_construction_price: 150,
						},
						{
							service_type: "R",
							item_id: 121101111,
							title:
								"Odstránenie ornice s vodor. premiestn. na hromady, so zložením na vzdialenosť do 100 m a nad 100m3",
							unit: "m3",
							quantity: 37.2,
							unit_delivery_price: 0,
							unit_construction_price: 2.12,
							total_delivery_price: 0,
							total_construction_price: 78.864,
						},
						{
							service_type: "R",
							item_id: 132201101,
							title: "Výkop ryhy do šírky 600 mm v horn.3 do 100 m3",
							unit: "m3",
							quantity: 60,
							unit_delivery_price: 0,
							unit_construction_price: 12.51,
							total_delivery_price: 0,
							total_construction_price: 750.6,
						},
						{
							service_type: "R",
							item_id: 122201102,
							title: "Odkopávka nezapažená v hornine3., nad 100 do 1000 m3",
							unit: "m3",
							quantity: 6.74,
							unit_delivery_price: 0,
							unit_construction_price: 3.78,
							total_delivery_price: 0,
							total_construction_price: 25.4772,
						},
						{
							service_type: "R",
							item_id: 162201101,
							title: "Vodorovné premiestnenie výkopku z horniny 1-4 do 20m",
							unit: "m3",
							quantity: 60,
							unit_delivery_price: 0,
							unit_construction_price: 7.21,
							total_delivery_price: 0,
							total_construction_price: 432.6,
						},
						{
							service_type: "R",
							item_id: 167101102,
							title:
								"Nakladanie neuľahnutého výkopku z hornín tr.1-4 nad 100 do 1000 m3",
							unit: "m3",
							quantity: 103.94,
							unit_delivery_price: 0,
							unit_construction_price: 2.91,
							total_delivery_price: 0,
							total_construction_price: 302.4654,
						},
						{
							service_type: "R",
							item_id: 171201202,
							title: "Uloženie sypaniny na skládky nad 100 do 1000 m3",
							unit: "m3",
							quantity: 103.94,
							unit_delivery_price: 0,
							unit_construction_price: 1.63,
							total_delivery_price: 0,
							total_construction_price: 169.42219999999998,
						},
					],
				},
				{
					info: {
						title: "Zakladanie",
						total_delivery_price: 10353.896949999998,
						total_construction_price: 1930.7211249999998,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 271573001,
							title:
								"Násyp pod základové konštrukcie so zhutnením zo štrkopiesku fr.32-63 mm",
							unit: "m3",
							quantity: 66.25,
							unit_delivery_price: 14.78,
							unit_construction_price: 3.47,
							total_delivery_price: 979.175,
							total_construction_price: 229.88750000000002,
						},
						{
							service_type: "R",
							item_id: 27332131,
							title:
								"Betón základových dosiek, železový (bez výstuže), tr. C 20/25",
							unit: "m3",
							quantity: 23.25,
							unit_delivery_price: 85.36,
							unit_construction_price: 22.12,
							total_delivery_price: 1984.62,
							total_construction_price: 514.2900000000001,
						},
						{
							service_type: "R",
							item_id: 273362422,
							title:
								"Výstuž základových dosiek zo zvár. sietí KARI, priemer drôtu 8 mm, veľkosť oka 150x150 mm",
							unit: "m2",
							quantity: 193.75,
							unit_delivery_price: 9.7,
							unit_construction_price: 0.78,
							total_delivery_price: 1879.3749999999998,
							total_construction_price: 151.125,
						},
						{
							service_type: "R",
							item_id: 274271300,
							title:
								"Murivo základových pásov (m3) PREMAC 50x40x25 s betónovou výplňou                    C 20/25 hr. 400 mm",
							unit: "m3",
							quantity: 1,
							unit_delivery_price: 136.24,
							unit_construction_price: 44.87,
							total_delivery_price: 136.24,
							total_construction_price: 44.87,
						},
						{
							service_type: "R",
							item_id: 274271303,
							title:
								"Murivo základových pásov (m3) PREMAC 50x30x25 s betónovou výplňou                    C 20/25 hr. 300 mm",
							unit: "m3",
							quantity: 15,
							unit_delivery_price: 134.88,
							unit_construction_price: 42.73,
							total_delivery_price: 2023.1999999999998,
							total_construction_price: 640.9499999999999,
						},
						{
							service_type: "R",
							item_id: 274271312,
							title:
								"Murivo základových pásov (m3) PREMAC 50x25x25 s betónovou výplňou                C 20/25 hr. 250 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 132.72,
							unit_construction_price: 40.56,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274271311,
							title:
								"Murivo základových pásov (m3) PREMAC 50x20x25 s betónovou výplňou                 C 20/25 hr. 200 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 131.59,
							unit_construction_price: 39.36,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274321312,
							title:
								"Betón základových pásov, železový (bez výstuže), tr. C 16/20",
							unit: "m3",
							quantity: 36,
							unit_delivery_price: 82.91,
							unit_construction_price: 8.37,
							total_delivery_price: 2984.7599999999998,
							total_construction_price: 301.32,
						},
						{
							service_type: "R",
							item_id: 274361825,
							title:
								"Výstuž pre murivo základových pásov PREMAC s betónovou výplňou z ocele 10505",
							unit: "t",
							quantity: 0.3875,
							unit_delivery_price: 945.876,
							unit_construction_price: 124.59,
							total_delivery_price: 366.52695,
							total_construction_price: 48.278625000000005,
						},
					],
				},
				{
					info: {
						title: "Zvislé konštrukcie",
						total_delivery_price: 703.075,
						total_construction_price: 204.36499999999998,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 451572111,
							title:
								"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z kameniva drobného ťaženého 0-4 mm",
							unit: "m3",
							quantity: 4,
							unit_delivery_price: 24,
							unit_construction_price: 17.97,
							total_delivery_price: 96,
							total_construction_price: 71.88,
						},
						{
							service_type: "R",
							item_id: 451573111,
							title:
								"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z piesku a štrkopiesku do 63 mm",
							unit: "m3",
							quantity: 2.5,
							unit_delivery_price: 21.07,
							unit_construction_price: 13.97,
							total_delivery_price: 52.675,
							total_construction_price: 34.925000000000004,
						},
						{
							service_type: "R",
							item_id: 2837650030,
							title:
								"Doska XPS STYRODUR 2800 C hr. 100 mm, zateplenie soklov, suterénov, podláh, ISOVER",
							unit: "m2",
							quantity: 36,
							unit_delivery_price: 13.89,
							unit_construction_price: 2.15,
							total_delivery_price: 500.04,
							total_construction_price: 77.39999999999999,
						},
						{
							"Č.": 20,
							service_type: "R",
							item_id: 283230000800,
							title:
								"Profilovaná fólia z PE DELTA-NB, rozmer 20x0,5m, pevnosť v tlaku 200 kN/m2, pre spodnú stavbu, DORKEN",
							unit: "m2",
							quantity: 36,
							unit_delivery_price: 1.51,
							unit_construction_price: 0.56,
							total_delivery_price: 54.36,
							total_construction_price: 20.160000000000004,
						},
					],
				},
				{
					info: {
						title: "Presun hmôt HSV",
						total_delivery_price: 0,
						total_construction_price: 321.99700000000007,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 998011001,
							title:
								"Presun hmôt pre budovy (801, 803, 812), zvislá konštr. z tehál, tvárnic, z kovu výšky do 6 m",
							unit: "t",
							quantity: 20.150000000000002,
							unit_delivery_price: 0,
							unit_construction_price: 15.98,
							total_delivery_price: 0,
							total_construction_price: 321.99700000000007,
						},
					],
				},
				{
					info: {
						title: "Práce a dodávky PSV",
						total_delivery_price: 1033.11,
						total_construction_price: 312.4,
						total: 0,
					},
					items: [],
				},
				{
					info: {
						title: "Zdravotechnika - vnútorná kanalizácia",
						total_delivery_price: 643.41,
						total_construction_price: 211.74,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 721171309,
							title: "Potrubie z rúr PE GEBERIT 125/4, 9 odpadné v zemi",
							unit: "m",
							quantity: 31,
							unit_delivery_price: 13.49,
							unit_construction_price: 5.07,
							total_delivery_price: 418.19,
							total_construction_price: 157.17000000000002,
						},
						{
							service_type: 286,
							item_id: "286510003800.S",
							title:
								"Koleno PVC-U, DN 125x15°, 30°, 45° pre pre hladký, kanalizačný, gravitačný systém",
							unit: "ks",
							quantity: 39,
							unit_delivery_price: 3.22,
							unit_construction_price: 0.64,
							total_delivery_price: 125.58000000000001,
							total_construction_price: 24.96,
						},
						{
							service_type: 286,
							item_id: 286130048900,
							title:
								"Rúra HDPE PE100 D 32x2,9 mm, dĺ. 100 m PN 16 (SDR11) pre tlakový rozvod pitnej vody, PIPELIFE",
							unit: "m",
							quantity: 47,
							unit_delivery_price: 2.12,
							unit_construction_price: 0.63,
							total_delivery_price: 99.64,
							total_construction_price: 29.61,
						},
					],
				},
				{
					info: {
						title: "Elektromontáže",
						total_delivery_price: 389.7,
						total_construction_price: 100.66,
						total: 0,
					},
					items: [
						{
							service_type: 345,
							item_id: 345710009300,
							title: "Rúrka ohybná vlnitá pancierová PVC-U, FXP DN 63",
							unit: "m",
							quantity: 40,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.25,
							total_delivery_price: 42,
							total_construction_price: 10,
						},
						{
							service_type: "R",
							item_id: 210220020,
							title: "Uzemňovacie vedenie v zemi FeZn vrátane izolácie spojov",
							unit: "bm",
							quantity: 66,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.51,
							total_delivery_price: 69.3,
							total_construction_price: 33.660000000000004,
						},
						{
							service_type: "R",
							item_id: 354410058800,
							title: "Pásovina uzemňovacia FeZn 30 x 4 mm",
							unit: "bm",
							quantity: 66,
							unit_delivery_price: 3.2,
							unit_construction_price: 0.5,
							total_delivery_price: 211.20000000000002,
							total_construction_price: 33,
						},
						{
							service_type: "R",
							item_id: 354410054800,
							title: "Drôt bleskozvodový FeZn, d 10mm",
							unit: "bm",
							quantity: 48,
							unit_delivery_price: 1.4,
							unit_construction_price: 0.5,
							total_delivery_price: 67.19999999999999,
							total_construction_price: 24,
						},
					],
				},
			],
		},
		{
			info: {
				title: "More ina sekcia",
				total_delivery_price: 0,
				total_construction_price: 1909.4288000000001,
				total: 0,
			},
			blocks: [
				{
					info: {
						title: "Zemné práce",
						total_delivery_price: 0,
						total_construction_price: 1909.4288000000001,
						total: 0,
					},
					items: [
						{
							service_type: 0,
							item_id: "000300016.S",
							title:
								"Geodetické práce - vykonávané pred výstavbou určenie vytyčovacej siete, vytýčenie staveniska, staveb. objektu",
							unit: "diel",
							quantity: 1,
							unit_delivery_price: 0,
							unit_construction_price: 150,
							total_delivery_price: 0,
							total_construction_price: 150,
						},
						{
							service_type: "R",
							item_id: 121101111,
							title:
								"Odstránenie ornice s vodor. premiestn. na hromady, so zložením na vzdialenosť do 100 m a nad 100m3",
							unit: "m3",
							quantity: 37.2,
							unit_delivery_price: 0,
							unit_construction_price: 2.12,
							total_delivery_price: 0,
							total_construction_price: 78.864,
						},
						{
							service_type: "R",
							item_id: 132201101,
							title: "Výkop ryhy do šírky 600 mm v horn.3 do 100 m3",
							unit: "m3",
							quantity: 60,
							unit_delivery_price: 0,
							unit_construction_price: 12.51,
							total_delivery_price: 0,
							total_construction_price: 750.6,
						},
						{
							service_type: "R",
							item_id: 122201102,
							title: "Odkopávka nezapažená v hornine3., nad 100 do 1000 m3",
							unit: "m3",
							quantity: 6.74,
							unit_delivery_price: 0,
							unit_construction_price: 3.78,
							total_delivery_price: 0,
							total_construction_price: 25.4772,
						},
						{
							service_type: "R",
							item_id: 162201101,
							title: "Vodorovné premiestnenie výkopku z horniny 1-4 do 20m",
							unit: "m3",
							quantity: 60,
							unit_delivery_price: 0,
							unit_construction_price: 7.21,
							total_delivery_price: 0,
							total_construction_price: 432.6,
						},
						{
							service_type: "R",
							item_id: 167101102,
							title:
								"Nakladanie neuľahnutého výkopku z hornín tr.1-4 nad 100 do 1000 m3",
							unit: "m3",
							quantity: 103.94,
							unit_delivery_price: 0,
							unit_construction_price: 2.91,
							total_delivery_price: 0,
							total_construction_price: 302.4654,
						},
						{
							service_type: "R",
							item_id: 171201202,
							title: "Uloženie sypaniny na skládky nad 100 do 1000 m3",
							unit: "m3",
							quantity: 103.94,
							unit_delivery_price: 0,
							unit_construction_price: 1.63,
							total_delivery_price: 0,
							total_construction_price: 169.42219999999998,
						},
					],
				},
				{
					info: {
						title: "Zakladanie",
						total_delivery_price: 10353.896949999998,
						total_construction_price: 1930.7211249999998,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 271573001,
							title:
								"Násyp pod základové konštrukcie so zhutnením zo štrkopiesku fr.32-63 mm",
							unit: "m3",
							quantity: 66.25,
							unit_delivery_price: 14.78,
							unit_construction_price: 3.47,
							total_delivery_price: 979.175,
							total_construction_price: 229.88750000000002,
						},
						{
							service_type: "R",
							item_id: 27332131,
							title:
								"Betón základových dosiek, železový (bez výstuže), tr. C 20/25",
							unit: "m3",
							quantity: 23.25,
							unit_delivery_price: 85.36,
							unit_construction_price: 22.12,
							total_delivery_price: 1984.62,
							total_construction_price: 514.2900000000001,
						},
						{
							service_type: "R",
							item_id: 273362422,
							title:
								"Výstuž základových dosiek zo zvár. sietí KARI, priemer drôtu 8 mm, veľkosť oka 150x150 mm",
							unit: "m2",
							quantity: 193.75,
							unit_delivery_price: 9.7,
							unit_construction_price: 0.78,
							total_delivery_price: 1879.3749999999998,
							total_construction_price: 151.125,
						},
						{
							service_type: "R",
							item_id: 274271300,
							title:
								"Murivo základových pásov (m3) PREMAC 50x40x25 s betónovou výplňou                    C 20/25 hr. 400 mm",
							unit: "m3",
							quantity: 1,
							unit_delivery_price: 136.24,
							unit_construction_price: 44.87,
							total_delivery_price: 136.24,
							total_construction_price: 44.87,
						},
						{
							service_type: "R",
							item_id: 274271303,
							title:
								"Murivo základových pásov (m3) PREMAC 50x30x25 s betónovou výplňou                    C 20/25 hr. 300 mm",
							unit: "m3",
							quantity: 15,
							unit_delivery_price: 134.88,
							unit_construction_price: 42.73,
							total_delivery_price: 2023.1999999999998,
							total_construction_price: 640.9499999999999,
						},
						{
							service_type: "R",
							item_id: 274271312,
							title:
								"Murivo základových pásov (m3) PREMAC 50x25x25 s betónovou výplňou                C 20/25 hr. 250 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 132.72,
							unit_construction_price: 40.56,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274271311,
							title:
								"Murivo základových pásov (m3) PREMAC 50x20x25 s betónovou výplňou                 C 20/25 hr. 200 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 131.59,
							unit_construction_price: 39.36,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274321312,
							title:
								"Betón základových pásov, železový (bez výstuže), tr. C 16/20",
							unit: "m3",
							quantity: 36,
							unit_delivery_price: 82.91,
							unit_construction_price: 8.37,
							total_delivery_price: 2984.7599999999998,
							total_construction_price: 301.32,
						},
						{
							service_type: "R",
							item_id: 274361825,
							title:
								"Výstuž pre murivo základových pásov PREMAC s betónovou výplňou z ocele 10505",
							unit: "t",
							quantity: 0.3875,
							unit_delivery_price: 945.876,
							unit_construction_price: 124.59,
							total_delivery_price: 366.52695,
							total_construction_price: 48.278625000000005,
						},
					],
				},
				{
					info: {
						title: "Zvislé konštrukcie",
						total_delivery_price: 703.075,
						total_construction_price: 204.36499999999998,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 451572111,
							title:
								"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z kameniva drobného ťaženého 0-4 mm",
							unit: "m3",
							quantity: 4,
							unit_delivery_price: 24,
							unit_construction_price: 17.97,
							total_delivery_price: 96,
							total_construction_price: 71.88,
						},
						{
							service_type: "R",
							item_id: 451573111,
							title:
								"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z piesku a štrkopiesku do 63 mm",
							unit: "m3",
							quantity: 2.5,
							unit_delivery_price: 21.07,
							unit_construction_price: 13.97,
							total_delivery_price: 52.675,
							total_construction_price: 34.925000000000004,
						},
						{
							service_type: "R",
							item_id: 2837650030,
							title:
								"Doska XPS STYRODUR 2800 C hr. 100 mm, zateplenie soklov, suterénov, podláh, ISOVER",
							unit: "m2",
							quantity: 36,
							unit_delivery_price: 13.89,
							unit_construction_price: 2.15,
							total_delivery_price: 500.04,
							total_construction_price: 77.39999999999999,
						},
						{
							"Č.": 20,
							service_type: "R",
							item_id: 283230000800,
							title:
								"Profilovaná fólia z PE DELTA-NB, rozmer 20x0,5m, pevnosť v tlaku 200 kN/m2, pre spodnú stavbu, DORKEN",
							unit: "m2",
							quantity: 36,
							unit_delivery_price: 1.51,
							unit_construction_price: 0.56,
							total_delivery_price: 54.36,
							total_construction_price: 20.160000000000004,
						},
					],
				},
				{
					info: {
						title: "Presun hmôt HSV",
						total_delivery_price: 0,
						total_construction_price: 321.99700000000007,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 998011001,
							title:
								"Presun hmôt pre budovy (801, 803, 812), zvislá konštr. z tehál, tvárnic, z kovu výšky do 6 m",
							unit: "t",
							quantity: 20.150000000000002,
							unit_delivery_price: 0,
							unit_construction_price: 15.98,
							total_delivery_price: 0,
							total_construction_price: 321.99700000000007,
						},
					],
				},
				{
					info: {
						title: "Práce a dodávky PSV",
						total_delivery_price: 1033.11,
						total_construction_price: 312.4,
						total: 0,
					},
					items: [],
				},
				{
					info: {
						title: "Zdravotechnika - vnútorná kanalizácia",
						total_delivery_price: 643.41,
						total_construction_price: 211.74,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 721171309,
							title: "Potrubie z rúr PE GEBERIT 125/4, 9 odpadné v zemi",
							unit: "m",
							quantity: 31,
							unit_delivery_price: 13.49,
							unit_construction_price: 5.07,
							total_delivery_price: 418.19,
							total_construction_price: 157.17000000000002,
						},
						{
							service_type: 286,
							item_id: "286510003800.S",
							title:
								"Koleno PVC-U, DN 125x15°, 30°, 45° pre pre hladký, kanalizačný, gravitačný systém",
							unit: "ks",
							quantity: 39,
							unit_delivery_price: 3.22,
							unit_construction_price: 0.64,
							total_delivery_price: 125.58000000000001,
							total_construction_price: 24.96,
						},
						{
							service_type: 286,
							item_id: 286130048900,
							title:
								"Rúra HDPE PE100 D 32x2,9 mm, dĺ. 100 m PN 16 (SDR11) pre tlakový rozvod pitnej vody, PIPELIFE",
							unit: "m",
							quantity: 47,
							unit_delivery_price: 2.12,
							unit_construction_price: 0.63,
							total_delivery_price: 99.64,
							total_construction_price: 29.61,
						},
					],
				},
				{
					info: {
						title: "Elektromontáže",
						total_delivery_price: 389.7,
						total_construction_price: 100.66,
						total: 0,
					},
					items: [
						{
							service_type: 345,
							item_id: 345710009300,
							title: "Rúrka ohybná vlnitá pancierová PVC-U, FXP DN 63",
							unit: "m",
							quantity: 40,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.25,
							total_delivery_price: 42,
							total_construction_price: 10,
						},
						{
							service_type: "R",
							item_id: 210220020,
							title: "Uzemňovacie vedenie v zemi FeZn vrátane izolácie spojov",
							unit: "bm",
							quantity: 66,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.51,
							total_delivery_price: 69.3,
							total_construction_price: 33.660000000000004,
						},
						{
							service_type: "R",
							item_id: 354410058800,
							title: "Pásovina uzemňovacia FeZn 30 x 4 mm",
							unit: "bm",
							quantity: 66,
							unit_delivery_price: 3.2,
							unit_construction_price: 0.5,
							total_delivery_price: 211.20000000000002,
							total_construction_price: 33,
						},
						{
							service_type: "R",
							item_id: 354410054800,
							title: "Drôt bleskozvodový FeZn, d 10mm",
							unit: "bm",
							quantity: 48,
							unit_delivery_price: 1.4,
							unit_construction_price: 0.5,
							total_delivery_price: 67.19999999999999,
							total_construction_price: 24,
						},
					],
				},
			],
		},
	],
};

const template = {
	customer: "Michal Gerhát",
	supplyer: {
		company_name: "STAV-IL s.r.o.",
		ico: "56 945 124",
		dic: "5487961254",
		phone: "0945687214",
		email: "stavil@gmail.com",
		web: "www.stavil.sk",
	},
	headers: [
		["kcn", "service_type"],
		["kp", "item_id"],
		["title", "title"],
		["mj", "unit"],
		["mc", "quantity"],
		["cdj", "unit_delivery_price"],
		["cmj", "unit_construction_price"],
		["cdc", "total_delivery_price"],
		["cmc", "total_construction_price"],
	],
	blocks: [
		{
			info: {
				title: "Zdravotechnika - vnútorná kanalizácia",
				total_delivery_price: 643.41,
				total_construction_price: 211.74,
				total_price: 123,
			},
			items: [
				{
					service_type: 345,
					item_id: 345710009300,
					title: "Rúrka ohybná vlnitá pancierová PVC-U, FXP DN 63",
					unit: "m",
					quantity: 40,
					unit_delivery_price: 1.05,
					unit_construction_price: 0.25,
					total_delivery_price: 643.41,
					total_construction_price: 211.74,
					total: 0,
				},
			],
		},
	],
};

export const template_config = [
	{
		id: "zaklady",
		label: "Základy",
		items: [
			{
				id: "ryhy",
				label: "Ryha",
				items: [
					{
						id: "dlzka",
						label: "Dĺžka",
						value: 160,
						unit: "m",
					},
					{
						id: "sirka",
						label: "Šírka",
						value: 60,
						unit: "m",
					},
					{
						id: "hlbka",
						label: "Hĺbka",
						value: 80,
						unit: "m",
					},
				],
			},
			{
				id: "obvod",
				label: "Obvod",
				value: 116,
				unit: "m",
			},
			{
				id: "obsah",
				label: "Obsah",
				value: 126,
				unit: "m2",
			},
			{
				id: "dt",
				label: "Dt",
				items: [
					{
						id: "30",
						label: "30",
						value: 130,
						unit: "ks",
					},
					{
						id: "20",
						label: "20",
						value: 0,
						unit: "ks",
					},
					{
						id: "40",
						label: "40",
						value: 20,
						unit: "ks",
					},
				],
			},
		],
	},
	{
		id: "murivo",
		label: "Murivo",
		items: [
			{
				id: "10",
				label: "10",
				value: 0,
				unit: "ks",
			},
			{
				id: "15",
				label: "15",
				value: 10,
				unit: "ks",
			},
			{
				id: "25",
				label: "25",
				value: 20,
				unit: "ks",
			},
			{
				id: "30",
				label: "30",
				value: 0,
				unit: "ks",
			},
			{
				id: "45",
				label: "45",
				value: 100,
				unit: "ks",
			},
		],
	},
	{
		id: "strecha",
		label: "Strecha",
		items: [
			{
				id: "obsah",
				label: "Obsah",
				value: 36,
				unit: "m2",
			},
		],
	},
];

export const empty = {
	customer: {
		name: "",
	},
	supplyer: {
		company_name: "",
		ico: "",
		dic: "",
		phone: "",
		email: "",
		web: "",
	},
	headers: [
		"service_type",
		"item_id",
		"title",
		"unit",
		"quantity",
		"unit_delivery_price",
		"unit_construction_price",
		"total_delivery_price",
		"total_construction_price",
		"total",
	],
	sections: [
		{
			info: {
				title: "Základová doska",
				total_delivery_price: 0,
				total_construction_price: 0,
				total: 0,
			},
			blocks: [
				{
					info: {
						title: "Zemné práce",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: 0,
							item_id: "000300016.S",
							title:
								"Geodetické práce - vykonávané pred výstavbou určenie vytyčovacej siete, vytýčenie staveniska, staveb. objektu",
							unit: "diel",
							quantity: 1,
							unit_delivery_price: 0,
							unit_construction_price: 150,
							total_delivery_price: 0,
							total_construction_price: 150,
						},
						{
							service_type: "R",
							item_id: 121101111,
							title:
								"Odstránenie ornice s vodor. premiestn. na hromady, so zložením na vzdialenosť do 100 m a nad 100m3",
							unit: "m3",
							quantity: 60,
							unit_delivery_price: 0,
							unit_construction_price: 2.12,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 132201101,
							title: "Výkop ryhy do šírky 600 mm v horn.3 do 100 m3",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 0,
							unit_construction_price: 12.51,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 122201102,
							title: "Odkopávka nezapažená v hornine, nad 100 do 1000 m3",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 0,
							unit_construction_price: 3.78,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 162201101,
							title: "Vodorovné premiestnenie výkopku z horniny 1-4 do 20m",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 0,
							unit_construction_price: 7.21,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 167101102,
							title:
								"Nakladanie neuľahnutého výkopku z hornín tr.1-4 nad 100 do 1000 m3",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 0,
							unit_construction_price: 2.91,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 171201202,
							title: "Uloženie sypaniny na skládky nad 100 do 1000 m3",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 0,
							unit_construction_price: 1.63,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
				{
					info: {
						title: "Zakladanie",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 271573001,
							title:
								"Násyp pod základové konštrukcie so zhutnením zo štrkopiesku fr.32-63 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 14.78,
							unit_construction_price: 3.47,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 27332131,
							title:
								"Betón základových dosiek, železový (bez výstuže), tr. C 20/25",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 85.36,
							unit_construction_price: 22.12,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 273362422,
							title:
								"Výstuž základových dosiek zo zvár. sietí KARI, priemer drôtu 8 mm, veľkosť oka 150x150 mm",
							unit: "m2",
							quantity: 0,
							unit_delivery_price: 9.7,
							unit_construction_price: 0.78,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274271300,
							title:
								"Murivo základových pásov (m3) PREMAC 50x40x25 s betónovou výplňou                    C 20/25 hr. 400 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 136.24,
							unit_construction_price: 44.87,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274271303,
							title:
								"Murivo základových pásov (m3) PREMAC 50x30x25 s betónovou výplňou                    C 20/25 hr. 300 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 134.88,
							unit_construction_price: 42.73,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274271312,
							title:
								"Murivo základových pásov (m3) PREMAC 50x25x25 s betónovou výplňou                C 20/25 hr. 250 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 132.72,
							unit_construction_price: 40.56,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274271311,
							title:
								"Murivo základových pásov (m3) PREMAC 50x20x25 s betónovou výplňou                 C 20/25 hr. 200 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 131.59,
							unit_construction_price: 39.36,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274321312,
							title:
								"Betón základových pásov, železový (bez výstuže), tr. C 16/20",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 82.91,
							unit_construction_price: 8.37,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 274361825,
							title:
								"Výstuž pre murivo základových pásov PREMAC s betónovou výplňou z ocele 10505",
							unit: "t",
							quantity: 0,
							unit_delivery_price: 945.876,
							unit_construction_price: 124.59,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
				{
					info: {
						title: "Zvislé konštrukcie",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 451572111,
							title:
								"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z kameniva drobného ťaženého 0-4 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 24,
							unit_construction_price: 17.97,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 451573111,
							title:
								"Lôžko pod potrubie, stoky a drobné objekty, v otvorenom výkope z piesku a štrkopiesku do 63 mm",
							unit: "m3",
							quantity: 0,
							unit_delivery_price: 21.07,
							unit_construction_price: 13.97,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 2837650030,
							title:
								"Doska XPS STYRODUR 2800 C hr. 100 mm, zateplenie soklov, suterénov, podláh, ISOVER",
							unit: "m2",
							quantity: 0,
							unit_delivery_price: 13.89,
							unit_construction_price: 2.15,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							"Č.": 20,
							service_type: "R",
							item_id: 283230000800,
							title:
								"Profilovaná fólia z PE DELTA-NB, rozmer 20x0,5m, pevnosť v tlaku 200 kN/m2, pre spodnú stavbu, DORKEN",
							unit: "m2",
							quantity: 0,
							unit_delivery_price: 1.51,
							unit_construction_price: 0.56,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
				{
					info: {
						title: "Presun hmôt HSV",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 998011001,
							title:
								"Presun hmôt pre budovy (801, 803, 812), zvislá konštr. z tehál, tvárnic, z kovu výšky do 6 m",
							unit: "t",
							quantity: 0,
							unit_delivery_price: 0,
							unit_construction_price: 15.98,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
				{
					info: {
						title: "Zdravotechnika - vnútorná kanalizácia",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: "R",
							item_id: 721171309,
							title: "Potrubie z rúr PE GEBERIT 125/4, 9 odpadné v zemi",
							unit: "m",
							quantity: 0,
							unit_delivery_price: 13.49,
							unit_construction_price: 5.07,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: 286,
							item_id: "286510003800.S",
							title:
								"Koleno PVC-U, DN 125x15°, 30°, 45° pre pre hladký, kanalizačný, gravitačný systém",
							unit: "ks",
							quantity: 0,
							unit_delivery_price: 3.22,
							unit_construction_price: 0.64,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: 286,
							item_id: 286130048900,
							title:
								"Rúra HDPE PE100 D 32x2,9 mm, dĺ. 100 m PN 16 (SDR11) pre tlakový rozvod pitnej vody, PIPELIFE",
							unit: "m",
							quantity: 0,
							unit_delivery_price: 2.12,
							unit_construction_price: 0.63,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
				{
					info: {
						title: "Elektromontáže",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: 345,
							item_id: 345710009300,
							title: "Rúrka ohybná vlnitá pancierová PVC-U, FXP DN 63",
							unit: "m",
							quantity: 0,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.25,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 210220020,
							title: "Uzemňovacie vedenie v zemi FeZn vrátane izolácie spojov",
							unit: "bm",
							quantity: 0,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.51,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 354410058800,
							title: "Pásovina uzemňovacia FeZn 30 x 4 mm",
							unit: "bm",
							quantity: 0,
							unit_delivery_price: 3.2,
							unit_construction_price: 0.5,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
						{
							service_type: "R",
							item_id: 354410054800,
							title: "Drôt bleskozvodový FeZn, d 10mm",
							unit: "bm",
							quantity: 0,
							unit_delivery_price: 1.4,
							unit_construction_price: 0.5,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
			],
		},
	],
};

export const customBuild = {
	customer: {
		name: "",
	},
	supplyer: {
		company_name: "",
		ico: "",
		dic: "",
		phone: "",
		email: "",
		web: "",
	},
	headers: [
		"service_type",
		"item_id",
		"title",
		"unit",
		"quantity",
		"unit_delivery_price",
		"unit_construction_price",
		"total_delivery_price",
		"total_construction_price",
		"total",
	],
	sections: [
		{
			info: {
				title: "Základová doska",
				total_delivery_price: 0,
				total_construction_price: 0,
				total: 0,
			},
			blocks: [
				{
					info: {
						title: "Názov",
						total_delivery_price: 0,
						total_construction_price: 0,
						total: 0,
					},
					items: [
						{
							service_type: 345,
							item_id: 345710009300,
							title: "Rúrka ohybná vlnitá pancierová PVC-U, FXP DN 63",
							unit: "m",
							quantity: 0,
							unit_delivery_price: 1.05,
							unit_construction_price: 0.25,
							total_delivery_price: 0,
							total_construction_price: 0,
						},
					],
				},
			],
		},
	],
};
